trigger:
  branches:
    include:
      - "develop"
      - "master"
  tags:
    include:
      - v*
  paths:
    exclude:
      - docs/*
      - README.md

pool:
  vmImage: "ubuntu-latest"

steps:
- task: UsePythonVersion@0
  displayName: "Use Python 3.10"
  inputs:
    versionSpec: 3.10

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: "install dependencies"
  
- script: |
    black --check src
  displayName: 'Check formatting with black'

- task: Docker@2
  displayName: "Build Docker Image"
  inputs:
    containerRegistry: 'ACR'
    repository: 'semantic_search-stable'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- task: Docker@2
  displayName: "Push Docker Image"
  inputs:
    containerRegistry: 'ACR'
    repository: 'semantic_search-stable'
    command: 'push'
    tags: |
      $(Build.BuildId)
      latest
